services:
    backend:
        build: backend
        restart: always
        command: npm run dev
        working_dir: /app
        volumes:
        - ./backend:/app
        environment:
            PORT: 3000
            MONGO_CONNECTION_STRING: mongodb://root:password@db:27017/stormboard?authSource=admin

    frontend:
        build: backend
        restart: always
        command: npm run dev
        working_dir: /app
        volumes:
        - ./frontend:/app
    db:
        image: mongo
        restart: always
        ports:
        - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    nginx:
        image: nginx:alpine
        restart: always
        ports:
        - 3000:8080
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - backend
        - frontend