services:
    backend:
        build: backend
        restart: always
        command: npm run dev
        working_dir: /app
        volumes:
        - ./backend:/app
        
    frontend:
        build: frontend
        restart: always
        command: react-scripts start
        working_dir: /app
        volumes:
        - ./frontend:/app
        environment:
            HOST: 0.0.0.0
    db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
    nginx:
        image: nginx:alpine
        restart: always
        ports:
        - 3000:8080
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - backend
        - frontend